### ISSUE TITLE
Incorrect comment

### ISSUE THREAD

**Issue by nyaray** [rajibahmed/dotfiles#1]
The comment says RUST, but the plugin is for elixir. Not a biggie, but I thought you should know ;P

https://github.com/rajibahmed/dotfiles/blob/3586eca94bba8954f7f059c906b9b45996a93eb0/nvim/init.vim#L66

**Comment by rajibahmed** [comment]
@nyaray ha ha you are peaking into my stupid dotfiles :) .. Will fix this major bug soon.
